tandibi2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  authenticate :user do
    resources :timelines,
      only: [:index, :show],
      param: :username
    resources :posts, only: [:create, :show]
  end
end

tandibi2/app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    @posts = Post.not_reply.where(user_id:[
      current_user.id,
      *current_user.followings.pluck(:id)
    ]).includes(postable: [:place]).order("created_at DESC")
  end

  def show
    @posts = Post.written_by(params[:username])
      .not_reply
      .order("created_at DESC")
  end
end

tandibi2/app/helpers/timelines_helper.rb
module TimelinesHelper
  def on_timeline?
    controller_path == "timelines"    
  end
  
  def on_bunch?
    on_timeline? && action_name == "index"
  end
  
  def on_self?
    on_timeline? && action_name == "show" && params[:username] == current_user.username
  end
end

tandibi2/app/views/timelines/_all.html.erb
<div class="timeline">
    <% @posts.each do |post| %>
        <div class="line-group">
            <%= render "timelines/line", post: post %>
        </div>
    <% end %>
</div>

tandibi2/app/views/timelines/_line.html.erb
<% user = post.user %>
<% postable = post.postable %>
<% show_replies = local_assigns.fetch(:show_replies, false) %>
<% pictures = post.pictures.with_attached_file %>

<%= render "layouts/inside_modal",
    title: "Send a reply",
    modal_class: "comment_modal_#{post.id}" do %>
    <%= render "posts/form", thread: post %>
<% end %>

<div class="picture-modals">
    <% pictures.each do |picture| %>
        <%= render "layouts/inside_modal",
            title: "",
            modal_class: "picture_modal_#{picture.id}" do %>
            <img src="<%= rails_blob_path(picture.file) %>" >
        <% end %>
    <% end %>
</div>

<div class="line flex" data-post-path="<%= post_path(post) %>">
    <div class="profile-container">
        <%= image_tag user.profile_picture_url %>
    </div>

    <div class="content">
        <div class="identifier">
            <%= link_to timeline_path(user) do %>
            <span class="name"><%= user.name %></span>
            <span class="username">@<%= user.username %></span>
            <% end %>
        </div>
        <% if postable.is_a?(Status) %>
            <%= simple_format post.postable.text %>
        <% elsif postable.is_a?(Sight) %>
            <div class="flex items-center">
                <%= evil_icon "ei-location" %>
                <p>
                    <%= postable.humanized_activity_type %>
                    <%= postable.place.name %>
                </p>
            </div>
        <% end %>
        <div class="pictures">
            <% pictures.each do |picture| %>
                <a href="#">
                <div class="picture js-modal-open"
                    data-modal-class="picture_modal_<%= picture.id %>">
                    <img src="<%= rails_blob_path(picture.file) %>">
                </div>
                </a>
            <% end %>
        </div>
        <div class="controls">
            <%= link_to "#" do %>
                <div class="control js-modal-open" data-modal-class="comment_modal_<%= post.id %>">
                <%= evil_icon "ei-comment" %>
                <% if post.replies.any? %>
                    <span>&nbsp;<%= post.replies.count %></span>
                <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<% if post.replies.any? %>
    <div class="replies">
        <% post.replies.each do |reply| %>
            <%= render "timelines/line", post: reply %>
        <% end %>
    </div>
<% end %>

tandibi2/app/views/timelines/index.html.erb
<%= render "posts/form" %>
<%= render "timelines/all" %>

tandibi2/app/views/timelines/show.html.erb
<%= render "timelines/all" %>